# [START django_app]
runtime: python37

# default_expiration: "4d 5h"

handlers:
# This configures Google App Engine to serve the files in the app's static
# directory.
- url: /static
  static_dir: static/
  secure: always

- url: /robots.txt
  static_files: shop/robots.txt
  upload: shop/robots.txt

- url: /sw.js
  static_files: shop/sw.js
  upload: shop/sw.js


# This handler routes all requests not caught above to your main app. It is
# required when static routes are defined, but can be omitted (along with
# the entire handlers section) when there are no static files defined.
- url: /.*
  script: auto
  secure: always
# [END django_app]
