version: '3'
services:
  mail:
    image: bytemark/smtp
    restart: always
    container_name: "smtp"
    environment:
      RELAY_HOST: smtp.bolls.life
      RELAY_PORT: 587
      RELAY_USERNAME: eggs@bolls.life
      RELAY_PASSWORD: secretpasswordowo