# Generated by Django 2.2.4 on 2019-09-02 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bible',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='', max_length=200)),
                ('short_name', models.CharField(default='', max_length=8)),
                ('language', models.CharField(default='', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Verse',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('b', models.IntegerField()),
                ('c', models.IntegerField()),
                ('v', models.IntegerField()),
                ('t', models.TextField()),
                ('bible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bolls.Bible')),
            ],
        ),
    ]
