# Generated by Django 2.2.4 on 2019-09-02 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='YLT',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('b', models.IntegerField()),
                ('c', models.IntegerField()),
                ('v', models.IntegerField()),
                ('t', models.TextField()),
            ],
        ),
    ]
