# Generated by Django 2.2.4 on 2019-10-05 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolls', '0002_ylt'),
    ]

    operations = [
        migrations.CreateModel(
            name='WLC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('general_link', models.CharField(max_length=12)),
                ('book', models.PositiveSmallIntegerField()),
                ('chapter', models.PositiveSmallIntegerField()),
                ('verse', models.PositiveSmallIntegerField()),
                ('text', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='verse',
            name='bible',
        ),
        migrations.DeleteModel(
            name='YLT',
        ),
        migrations.DeleteModel(
            name='Bible',
        ),
        migrations.DeleteModel(
            name='Verse',
        ),
    ]
