# Generated by Django 2.2.4 on 2019-10-08 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolls', '0003_auto_20191005_2126'),
    ]

    operations = [
        migrations.CreateModel(
            name='Verses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation', models.CharField(max_length=120)),
                ('book', models.PositiveSmallIntegerField()),
                ('chapter', models.PositiveSmallIntegerField()),
                ('verse', models.PositiveSmallIntegerField()),
                ('text', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='WLC',
        ),
    ]
