# Generated by Django 2.1.7 on 2019-11-02 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolls', '0005_bookmarks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmarks',
            name='background',
        ),
        migrations.AlterField(
            model_name='bookmarks',
            name='color',
            field=models.CharField(max_length=32),
        ),
        migrations.RemoveField(
            model_name='bookmarks',
            name='creationdate',
        ),
    ]
