# Generated by Django 2.1.7 on 2019-11-02 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolls', '0006_auto_20191102_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmarks',
            name='date',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
