# Generated by Django 2.1.7 on 2019-11-02 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolls', '0007_auto_20191102_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmarks',
            name='labels',
            field=models.CharField(default=None, max_length=150),
        ),
        migrations.AlterField(
            model_name='bookmarks',
            name='note',
            field=models.TextField(default=None),
        ),
    ]
