# Generated by Django 2.1.7 on 2019-11-03 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bolls', '0008_auto_20191102_2202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmarks',
            name='labels',
        ),
    ]
