# Generated by Django 4.0 on 2021-12-15 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionary',
            name='short_definition',
            field=models.TextField(null=True),
        ),
    ]
