# Generated by Django 4.0 on 2021-12-15 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolls', '0002_alter_dictionary_short_definition'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictionary',
            name='dictionary',
            field=models.CharField(default='kaka', max_length=8),
            preserve_default=False,
        ),
    ]
