# Generated by Django 4.0 on 2021-12-15 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolls', '0004_alter_dictionary_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionary',
            name='lexeme',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='dictionary',
            name='topic',
            field=models.TextField(),
        ),
    ]
