# Generated by Django 4.0 on 2021-12-15 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolls', '0005_alter_dictionary_lexeme_alter_dictionary_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionary',
            name='lexeme',
            field=models.TextField(),
        ),
    ]
