# Generated by Django 4.0 on 2022-01-12 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolls', '0006_alter_dictionary_lexeme'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='purge_date',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
