# Generated by Django 4.0.2 on 2022-02-17 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bolls', '0007_history_purge_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmarks',
            name='note',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='bolls.note'),
        ),
    ]
