# Generated by Django 4.0.4 on 2022-10-10 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolls', '0008_alter_bookmarks_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='compare_translations',
            field=models.TextField(null=True, default=None),
        ),
    ]
