# Generated by Django 4.0.4 on 2022-12-11 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolls', '0009_history_compare_translations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='history',
            field=models.TextField(),
        ),
    ]
