# Generated by Django 5.0.1 on 2024-09-13 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolls', '0010_alter_history_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='favorite_translations',
            field=models.TextField(default=None, null=True),
        ),
    ]
