# Generated by Django 5.1.6 on 2025-02-13 21:31

from django.db import migrations, models
from django.contrib.postgres.operations import AddIndexConcurrently


class Migration(migrations.Migration):

    dependencies = [
        ('bolls', '0011_history_favorite_translations'),
    ]

    operations = [
        AddIndexConcurrently(
            model_name='verses',
            index=models.Index(fields=['translation', 'book', 'chapter'], name='bolls_verse_transla_b7c462_idx'),
        ),
        AddIndexConcurrently(
            model_name='verses',
            index=models.Index(fields=['translation', 'book', 'chapter', 'verse'], name='bolls_verse_transla_23fd2d_idx'),
        ),
    ]

    atomic = False
