# Generated by Django 5.1.6 on 2025-02-13 21:39

from django.db import migrations, models
from django.contrib.postgres.operations import AddIndexConcurrently


class Migration(migrations.Migration):

    dependencies = [
        ('bolls', '0012_verses_bolls_verse_transla_b7c462_idx_and_more'),
    ]

    operations = [
        AddIndexConcurrently(
            model_name='commentary',
            index=models.Index(fields=['translation', 'book', 'chapter'], name='bolls_comme_transla_851084_idx'),
        ),
        AddIndexConcurrently(
            model_name='commentary',
            index=models.Index(fields=['translation', 'book', 'chapter', 'verse'], name='bolls_comme_transla_08dfc3_idx'),
        ),
    ]

    atomic = False
