# Generated by Django 5.1.6 on 2026-04-11 00:00

from django.contrib.postgres.indexes import GinIndex
from django.contrib.postgres.operations import AddIndexConcurrently
from django.contrib.postgres.search import SearchVector
from django.db import migrations, models
from django.db.models import F, Func


class Migration(migrations.Migration):
    dependencies = [
        ("bolls", "0013_commentary_bolls_comme_transla_851084_idx_and_more"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE FUNCTION immutable_unaccent(text)
            RETURNS text AS $$
                SELECT public.unaccent('public.unaccent', $1)
            $$ LANGUAGE sql IMMUTABLE PARALLEL SAFE STRICT;
            """,
            reverse_sql="DROP FUNCTION IF EXISTS immutable_unaccent(text);",
        ),
        AddIndexConcurrently(
            model_name="dictionary",
            index=GinIndex(
                SearchVector(
                    Func(F("lexeme"), function="immutable_unaccent"),
                    config="simple",
                ),
                name="bolls_dict_lexeme_unaccent_idx",
            ),
        ),
        AddIndexConcurrently(
            model_name="dictionary",
            index=models.Index(fields=["topic"], name="bolls_dict_topic_idx"),
        ),
    ]

    atomic = False
