# Generated by Django 6.0.7 on 2026-07-16 13:29

import pgvector.django.indexes
import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bolls", "0014_dictionary_search_indexes"),
    ]

    operations = [
        pgvector.django.VectorExtension(),
        migrations.AddField(
            model_name="verses",
            name="embedding",
            field=pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True),
        ),
        migrations.AddIndex(
            model_name="verses",
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=["embedding"], m=16, name="text_vector_index", opclasses=["vector_cosine_ops"]),
        ),
    ]
