add_header 'Access-Control-Allow-Origin' '*' always;
add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,X-CSRFToken,Content-Type,Range,Accept,Origin' always;
add_header 'Access-Control-Expose-Headers' 'Content-Length,Content-Range,Exact_matches' always;
add_header "Access-Control-Max-Age" "1000" always;
add_header "Cross-Origin-Opener-Policy" "unsafe-none" always;
add_header "Cross-Origin-Embedder-Policy" "unsafe-none" always;
add_header "Cross-Origin-Resource-Policy" "cross-origin" always;
add_header "Content-Security-Policy" "cross-origin" always;
add_header "referrer-policy" "unsafe-url" always;
add_header "x-frame-options" "*" always;