http:
  routers:
    traefik:
      rule: "Host(`${bolls.local:-traefik.localhost}`)"
      service: "api@internal"

tls:
  certificates:
    - certFile: "/etc/certs/local-cert.pem"
      keyFile: "/etc/certs/local-key.pem"
