on:
  push:
    tags:
      - v**
    # branches:
    #   - master

  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release'
        required: true
        default: '0.0.0'

jobs:
  build:
    name: Build and Push Docker Image to GitHub Container Registry
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - uses: actions/checkout@v3
      - name: build django image for ghcr
        run: |
          echo ${{ secrets.GH_PAT }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          REPO_LOWER=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          docker build -t ghcr.io/$REPO_LOWER/django:latest -f ./django/Dockerfile ./django
          docker push ghcr.io/$REPO_LOWER/django:latest

  deploy:
    name: Deploy to Prod
    runs-on: ubuntu-latest
    needs: build
    environment: prod
    env:
      DEBUG_SECRET: ${{ secrets.DEBUG_SECRET }}
      NGINX_DOMAIN_NAME: ${{ secrets.NGINX_DOMAIN_NAME }}
      POSTGRES_DB_SECRET: ${{ secrets.POSTGRES_DB_SECRET }}
      POSTGRES_PASSWORD_SECRET: ${{ secrets.POSTGRES_PASSWORD_SECRET }}
      POSTGRES_USER_SECRET: ${{ secrets.POSTGRES_USER_SECRET }}
      SECRET_KEY_SECRET: ${{ secrets.SECRET_KEY_SECRET }}
      DJANGO_ALLOWED_HOSTS_SECRET: ${{ vars.DJANGO_ALLOWED_HOSTS_SECRET }}
      EMAIL_HOST_PASSWORD_SECRET: ${{ secrets.EMAIL_HOST_PASSWORD_SECRET }}
      EMAIL_HOST_USER_SECRET: ${{ secrets.EMAIL_HOST_USER_SECRET }}
      SOCIAL_AUTH_GOOGLE_OAUTH2_KEY_SECRET: ${{ secrets.SOCIAL_AUTH_GOOGLE_OAUTH2_KEY_SECRET }}
      SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET_SECRET: ${{ secrets.SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET_SECRET }}
      SOCIAL_AUTH_GITHUB_KEY_SECRET: ${{ secrets.SOCIAL_AUTH_GITHUB_KEY_SECRET }}
      SOCIAL_AUTH_GITHUB_SECRET_SECRET: ${{ secrets.SOCIAL_AUTH_GITHUB_SECRET_SECRET }}

    steps:
      - name: SSH and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          envs: DEBUG_SECRET,SECRET_KEY_SECRET,DJANGO_ALLOWED_HOSTS_SECRET,POSTGRES_DB_SECRET,EMAIL_HOST_PASSWORD_SECRET,EMAIL_HOST_USER_SECRET,SOCIAL_AUTH_GOOGLE_OAUTH2_KEY_SECRET,SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET_SECRET,SOCIAL_AUTH_GITHUB_KEY_SECRET,SOCIAL_AUTH_GITHUB_SECRET_SECRET,POSTGRES_USER_SECRET,POSTGRES_PASSWORD_SECRET,NGINX_DOMAIN_NAME
          script: |
            rm -rf bain
            git clone https://github.com/Bolls-Bible/bain
            cd bain
            git checkout ${{ github.ref }}

            echo "Injecting secrets..."
            sed -i "s/DEBUG_SECRET/$DEBUG_SECRET/g" nerdctl-compose.prod.yaml
            sed -i "s/SECRET_KEY_SECRET/$SECRET_KEY_SECRET/g" nerdctl-compose.prod.yaml
            sed -i "s/DJANGO_ALLOWED_HOSTS_SECRET/$DJANGO_ALLOWED_HOSTS_SECRET/g" nerdctl-compose.prod.yaml
            sed -i "s/POSTGRES_DB_SECRET/$POSTGRES_DB_SECRET/g" nerdctl-compose.prod.yaml
            sed -i "s/EMAIL_HOST_PASSWORD_SECRET/$EMAIL_HOST_PASSWORD_SECRET/g" nerdctl-compose.prod.yaml
            sed -i "s/EMAIL_HOST_USER_SECRET/$EMAIL_HOST_USER_SECRET/g" nerdctl-compose.prod.yaml
            sed -i "s/SOCIAL_AUTH_GOOGLE_OAUTH2_KEY_SECRET/$SOCIAL_AUTH_GOOGLE_OAUTH2_KEY_SECRET/g" nerdctl-compose.prod.yaml
            sed -i "s/SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET_SECRET/$SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET_SECRET/g" nerdctl-compose.prod.yaml
            sed -i "s/SOCIAL_AUTH_GITHUB_KEY_SECRET/$SOCIAL_AUTH_GITHUB_KEY_SECRET/g" nerdctl-compose.prod.yaml
            sed -i "s/SOCIAL_AUTH_GITHUB_SECRET_SECRET/$SOCIAL_AUTH_GITHUB_SECRET_SECRET/g" nerdctl-compose.prod.yaml
            sed -i "s/POSTGRES_USER_SECRET/$POSTGRES_USER_SECRET/g" nerdctl-compose.prod.yaml
            sed -i "s/POSTGRES_PASSWORD_SECRET/$POSTGRES_PASSWORD_SECRET/g" nerdctl-compose.prod.yaml
            sed -i "s/NGINX_DOMAIN_NAME/$NGINX_DOMAIN_NAME/g" nerdctl-compose.prod.yaml

            echo "Setting up environment..."
            sudo sysctl -w net.ipv4.ip_unprivileged_port_start=80
            echo "net.ipv4.ip_unprivileged_port_start=80" | sudo tee /etc/sysctl.d/99-nerdctl-ports.conf

            nerdctl network create web
            nerdctl network create internal

            curl -s https://raw.githubusercontent.com/certbot/certbot/master/certbot-nginx/certbot_nginx/_internal/tls_configs/options-ssl-nginx.conf >"/var/letsencrypt/options-ssl-nginx.conf"
            curl -s https://raw.githubusercontent.com/certbot/certbot/master/certbot/certbot/ssl-dhparams.pem >"/var/letsencrypt/ssl-dhparams.pem"

            sh ./init-certs/check-certs.sh

            echo "Pulling latest image..."
            nerdctl pull  ghcr.io/bolls-bible/bain/django

            echo "Starting deploy..."
            nerdctl compose -f nerdctl-compose.prod.yaml up -d --force-recreate web
            nerdctl restart nginx

            nerdctl cp ./sql/unaccent_plus.rules db:/usr/share/postgresql/18/tsearch_data/unaccent_plus.rules
            nerdctl exec db psql -U $POSTGRES_USER_SECRET -d $POSTGRES_DB_SECRET -c "CREATE EXTENSION unaccent;"
            nerdctl exec db psql -U $POSTGRES_USER_SECRET -d $POSTGRES_DB_SECRET -c "ALTER TEXT SEARCH DICTIONARY unaccent (RULES='unaccent_plus')"
            nerdctl exec db psql -U $POSTGRES_USER_SECRET -d $POSTGRES_DB_SECRET -c "CREATE EXTENSION pg_trgm"

            echo "Running tests..."
            nerdctl exec web python manage.py test --keepdb
            # nerdctl system prune -a -f # nerdctl is so nerdy that it says clean on its own
            echo "Done."
