# on:
#   push:
#     branches:
#       - master
#     tags:
#       - v**

on:
  push:
    braches:
      - master

jobs:
  deploy:
    name: Deploy to Prod
    runs-on: ubuntu-latest
    environment: prod
    steps:
      # - name: SSH and Deploy
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: ${{ secrets.SSH_HOST }}
      #     username: ${{ secrets.SSH_USERNAME }}
      #     key: ${{ secrets.SSH_KEY }}
      #     port: ${{ secrets.SSH_PORT }}


      #     env:
      #       DEBUG_SECRET: ${{ secrets.DEBUG_SECRET }}
      #       SECRET_KEY_SECRET: ${{ secrets.SECRET_KEY_SECRET }}
      #       DJANGO_ALLOWED_HOSTS_SECRET: ${{ secrets.DJANGO_ALLOWED_HOSTS_SECRET }}
      #       SQL_ENGINE_SECRET: ${{ secrets.SQL_ENGINE_SECRET }}
      #       SQL_DATABASE_SECRET: ${{ secrets.SQL_DATABASE_SECRET }}
      #       SQL_USER_SECRET: ${{ secrets.SQL_USER_SECRET }}
      #       SQL_PASSWORD_SECRET: ${{ secrets.SQL_PASSWORD_SECRET }}
      #       SQL_HOST_SECRET: ${{ secrets.SQL_HOST_SECRET }}
      #       SQL_PORT_SECRET: ${{ secrets.SQL_PORT_SECRET }}
      #       DATABASE_SECRET: ${{ secrets.DATABASE_SECRET }}
      #       EMAIL_HOST_PASSWORD_SECRET: ${{ secrets.EMAIL_HOST_PASSWORD_SECRET }}
      #       EMAIL_HOST_USER_SECRET: ${{ secrets.EMAIL_HOST_USER_SECRET }}
      #       SOCIAL_AUTH_GOOGLE_OAUTH2_KEY_SECRET: ${{ secrets.SOCIAL_AUTH_GOOGLE_OAUTH2_KEY_SECRET }}
      #       SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET_SECRET: ${{ secrets.SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET_SECRET }}
      #       SOCIAL_AUTH_GITHUB_KEY_SECRET: ${{ secrets.SOCIAL_AUTH_GITHUB_KEY_SECRET }}
      #       SOCIAL_AUTH_GITHUB_SECRET_SECRET: ${{ secrets.SOCIAL_AUTH_GITHUB_SECRET_SECRET }}
      #     script: |
      #       git clone https://github.com/Bolls-Bible/bain
      #       cd bain
      #       sed -i "s/DEBUG_SECRET/$DEBUG_SECRET/g" docker-compose.yml
      #       sed -i "s/SECRET_KEY_SECRET/$SECRET_KEY_SECRET/g" docker-compose.yml
      #       sed -i "s/DJANGO_ALLOWED_HOSTS_SECRET/$DJANGO_ALLOWED_HOSTS_SECRET/g" docker-compose.yml
      #       sed -i "s/SQL_ENGINE_SECRET/$SQL_ENGINE_SECRET/g" docker-compose.yml
      #       sed -i "s/SQL_DATABASE_SECRET/$SQL_DATABASE_SECRET/g" docker-compose.yml
      #       sed -i "s/SQL_USER_SECRET/$SQL_USER_SECRET/g" docker-compose.yml
      #       sed -i "s/SQL_PASSWORD_SECRET/$SQL_PASSWORD_SECRET/g" docker-compose.yml
      #       sed -i "s/SQL_HOST_SECRET/$SQL_HOST_SECRET/g" docker-compose.yml
      #       sed -i "s/SQL_PORT_SECRET/$SQL_PORT_SECRET/g" docker-compose.yml
      #       sed -i "s/DATABASE_SECRET/$DATABASE_SECRET/g" docker-compose.yml
      #       sed -i "s/EMAIL_HOST_PASSWORD_SECRET/$EMAIL_HOST_PASSWORD_SECRET/g" docker-compose.yml
      #       sed -i "s/EMAIL_HOST_USER_SECRET/$EMAIL_HOST_USER_SECRET/g" docker-compose.yml
      #       sed -i "s/SOCIAL_AUTH_GOOGLE_OAUTH2_KEY_SECRET/$SOCIAL_AUTH_GOOGLE_OAUTH2_KEY_SECRET/g" docker-compose.yml
      #       sed -i "s/SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET_SECRET/$SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET_SECRET/g" docker-compose.yml
      #       sed -i "s/SOCIAL_AUTH_GITHUB_KEY_SECRET/$SOCIAL_AUTH_GITHUB_KEY_SECRET/g" docker-compose.yml
      #       sed -i "s/SOCIAL_AUTH_GITHUB_SECRET_SECRET/$SOCIAL_AUTH_GITHUB_SECRET_SECRET/g" docker-compose.yml
      #       docker-compose up -d
      #       cd ..
      #       rm -fr bain

      - name: SSH and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          env:
            DEBUG_SECRET: ${{ secrets.DEBUG_SECRET }}
          script: |
            echo "github was here $DEBUG_SECRET" > file.txt